.TH "toxic_vision.async_kinect_publisher.ImagePublisher" 3 "Wed Sep 6 2023" "The Toxic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toxic_vision.async_kinect_publisher.ImagePublisher
.SH SYNOPSIS
.br
.PP
.PP
Inherits Node\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBtimer_callback\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpublisher_\fP"
.br
.ti -1c
.RI "\fBframe\fP"
.br
.ti -1c
.RI "\fBtimer\fP"
.br
.ti -1c
.RI "\fBbgr_frame\fP"
.br
.ti -1c
.RI "\fBbr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Toxic from the source code\&.
