.TH "toxic_hardware.roboclaw_3.Roboclaw.Cmd" 3 "Wed Sep 6 2023" "The Toxic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
toxic_hardware.roboclaw_3.Roboclaw.Cmd
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBM1FORWARD\fP = 0"
.br
.ti -1c
.RI "int \fBM1BACKWARD\fP = 1"
.br
.ti -1c
.RI "int \fBSETMINMB\fP = 2"
.br
.ti -1c
.RI "int \fBSETMAXMB\fP = 3"
.br
.ti -1c
.RI "int \fBM2FORWARD\fP = 4"
.br
.ti -1c
.RI "int \fBM2BACKWARD\fP = 5"
.br
.ti -1c
.RI "int \fBM17BIT\fP = 6"
.br
.ti -1c
.RI "int \fBM27BIT\fP = 7"
.br
.ti -1c
.RI "int \fBMIXEDFORWARD\fP = 8"
.br
.ti -1c
.RI "int \fBMIXEDBACKWARD\fP = 9"
.br
.ti -1c
.RI "int \fBMIXEDRIGHT\fP = 10"
.br
.ti -1c
.RI "int \fBMIXEDLEFT\fP = 11"
.br
.ti -1c
.RI "int \fBMIXEDFB\fP = 12"
.br
.ti -1c
.RI "int \fBMIXEDLR\fP = 13"
.br
.ti -1c
.RI "int \fBGETM1ENC\fP = 16"
.br
.ti -1c
.RI "int \fBGETM2ENC\fP = 17"
.br
.ti -1c
.RI "int \fBGETM1SPEED\fP = 18"
.br
.ti -1c
.RI "int \fBGETM2SPEED\fP = 19"
.br
.ti -1c
.RI "int \fBRESETENC\fP = 20"
.br
.ti -1c
.RI "int \fBGETVERSION\fP = 21"
.br
.ti -1c
.RI "int \fBSETM1ENCCOUNT\fP = 22"
.br
.ti -1c
.RI "int \fBSETM2ENCCOUNT\fP = 23"
.br
.ti -1c
.RI "int \fBGETMBATT\fP = 24"
.br
.ti -1c
.RI "int \fBGETLBATT\fP = 25"
.br
.ti -1c
.RI "int \fBSETMINLB\fP = 26"
.br
.ti -1c
.RI "int \fBSETMAXLB\fP = 27"
.br
.ti -1c
.RI "int \fBSETM1PID\fP = 28"
.br
.ti -1c
.RI "int \fBSETM2PID\fP = 29"
.br
.ti -1c
.RI "int \fBGETM1ISPEED\fP = 30"
.br
.ti -1c
.RI "int \fBGETM2ISPEED\fP = 31"
.br
.ti -1c
.RI "int \fBM1DUTY\fP = 32"
.br
.ti -1c
.RI "int \fBM2DUTY\fP = 33"
.br
.ti -1c
.RI "int \fBMIXEDDUTY\fP = 34"
.br
.ti -1c
.RI "int \fBM1SPEED\fP = 35"
.br
.ti -1c
.RI "int \fBM2SPEED\fP = 36"
.br
.ti -1c
.RI "int \fBMIXEDSPEED\fP = 37"
.br
.ti -1c
.RI "int \fBM1SPEEDACCEL\fP = 38"
.br
.ti -1c
.RI "int \fBM2SPEEDACCEL\fP = 39"
.br
.ti -1c
.RI "int \fBMIXEDSPEEDACCEL\fP = 40"
.br
.ti -1c
.RI "int \fBM1SPEEDDIST\fP = 41"
.br
.ti -1c
.RI "int \fBM2SPEEDDIST\fP = 42"
.br
.ti -1c
.RI "int \fBMIXEDSPEEDDIST\fP = 43"
.br
.ti -1c
.RI "int \fBM1SPEEDACCELDIST\fP = 44"
.br
.ti -1c
.RI "int \fBM2SPEEDACCELDIST\fP = 45"
.br
.ti -1c
.RI "int \fBMIXEDSPEEDACCELDIST\fP = 46"
.br
.ti -1c
.RI "int \fBGETBUFFERS\fP = 47"
.br
.ti -1c
.RI "int \fBGETPWMS\fP = 48"
.br
.ti -1c
.RI "int \fBGETCURRENTS\fP = 49"
.br
.ti -1c
.RI "int \fBMIXEDSPEED2ACCEL\fP = 50"
.br
.ti -1c
.RI "int \fBMIXEDSPEED2ACCELDIST\fP = 51"
.br
.ti -1c
.RI "int \fBM1DUTYACCEL\fP = 52"
.br
.ti -1c
.RI "int \fBM2DUTYACCEL\fP = 53"
.br
.ti -1c
.RI "int \fBMIXEDDUTYACCEL\fP = 54"
.br
.ti -1c
.RI "int \fBREADM1PID\fP = 55"
.br
.ti -1c
.RI "int \fBREADM2PID\fP = 56"
.br
.ti -1c
.RI "int \fBSETMAINVOLTAGES\fP = 57"
.br
.ti -1c
.RI "int \fBSETLOGICVOLTAGES\fP = 58"
.br
.ti -1c
.RI "int \fBGETMINMAXMAINVOLTAGES\fP = 59"
.br
.ti -1c
.RI "int \fBGETMINMAXLOGICVOLTAGES\fP = 60"
.br
.ti -1c
.RI "int \fBSETM1POSPID\fP = 61"
.br
.ti -1c
.RI "int \fBSETM2POSPID\fP = 62"
.br
.ti -1c
.RI "int \fBREADM1POSPID\fP = 63"
.br
.ti -1c
.RI "int \fBREADM2POSPID\fP = 64"
.br
.ti -1c
.RI "int \fBM1SPEEDACCELDECCELPOS\fP = 65"
.br
.ti -1c
.RI "int \fBM2SPEEDACCELDECCELPOS\fP = 66"
.br
.ti -1c
.RI "int \fBMIXEDSPEEDACCELDECCELPOS\fP = 67"
.br
.ti -1c
.RI "int \fBSETM1DEFAULTACCEL\fP = 68"
.br
.ti -1c
.RI "int \fBSETM2DEFAULTACCEL\fP = 69"
.br
.ti -1c
.RI "int \fBSETPINFUNCTIONS\fP = 74"
.br
.ti -1c
.RI "int \fBGETPINFUNCTIONS\fP = 75"
.br
.ti -1c
.RI "int \fBSETDEADBAND\fP = 76"
.br
.ti -1c
.RI "int \fBGETDEADBAND\fP = 77"
.br
.ti -1c
.RI "int \fBRESTOREDEFAULTS\fP = 80"
.br
.ti -1c
.RI "int \fBGETTEMP\fP = 82"
.br
.ti -1c
.RI "int \fBGETTEMP2\fP = 83"
.br
.ti -1c
.RI "int \fBGETERROR\fP = 90"
.br
.ti -1c
.RI "int \fBGETENCODERMODE\fP = 91"
.br
.ti -1c
.RI "int \fBSETM1ENCODERMODE\fP = 92"
.br
.ti -1c
.RI "int \fBSETM2ENCODERMODE\fP = 93"
.br
.ti -1c
.RI "int \fBWRITENVM\fP = 94"
.br
.ti -1c
.RI "int \fBREADNVM\fP = 95"
.br
.ti -1c
.RI "int \fBSETCONFIG\fP = 98"
.br
.ti -1c
.RI "int \fBGETCONFIG\fP = 99"
.br
.ti -1c
.RI "int \fBSETM1MAXCURRENT\fP = 133"
.br
.ti -1c
.RI "int \fBSETM2MAXCURRENT\fP = 134"
.br
.ti -1c
.RI "int \fBGETM1MAXCURRENT\fP = 135"
.br
.ti -1c
.RI "int \fBGETM2MAXCURRENT\fP = 136"
.br
.ti -1c
.RI "int \fBSETPWMMODE\fP = 148"
.br
.ti -1c
.RI "int \fBGETPWMMODE\fP = 149"
.br
.ti -1c
.RI "int \fBREADEEPROM\fP = 252"
.br
.ti -1c
.RI "int \fBWRITEEEPROM\fP = 253"
.br
.ti -1c
.RI "int \fBFLAGBOOTLOADER\fP = 255"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Toxic from the source code\&.
